import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Banner from '@/components/Banner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Cafe Finder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Cafe Finder</h1>
        <Banner />
      </main>
    </>
  );
}
